/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;


import ticket.booking.Util.UserServiceUtil;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Ticket Booking System...");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("Something is wrong with your app not able to create a userBookingService Object");
        }

        System.out.println("1. Sign up");
        System.out.println("2. Login");
        System.out.println("3. Fetch Bookings");
        System.out.println("4. Search Trains");
        System.out.println("5. Book a Seat");
        System.out.println("6. Cancel My Booking");
        System.out.println("7. Exit the App");

        option = scanner.nextInt();
        while (option != 7) {
            switch (option) {
                case 1:
                    System.out.println("Enter the username");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter your passoword");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter your passoword");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException ex) {
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetching Bookings...");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Type you source");
                    String src = scanner.next();

                    System.out.println("Type you destination");
                    String destination = scanner.next();

                    List<Train> trainsFromSrcToDestination = userBookingService.searchTrains(src, destination);
                    break;

            }

        }
    }
}
